### ISSUE TITLE
Lograge custom ignore blowing up.

### ISSUE THREAD

**Issue by jpslav** [openstax/exchange#41]
[This line is blowing up](https://github.com/openstax/exchange/blob/361896541b71a5ce0e4e1c15407a231738ff3b5a/config/environments/production.rb#L103) with exception message:

> Sep 30 19:10:10 server1.exchange-kev.openstax.org exchange_rails:  E, [2015-10-01T02:10:03.123126 #22151] ERROR -- : [198.20.69.74] Could not log "process_action.action_controller" event. NoMethodError: undefined method `path' for #<ActiveSupport::Notifications::Event:0x007f0b5e3477c0> ["/home/ostexchange/src/exchange-3ab9282/config/environments/production.rb:103:in `block (2 levels) in <top (required)>'", "/home/ostexchange/src/exchange-3ab9282/vendor/bundle/ruby/2.1.0/gems/lograge-0.3.4/lib/lograge.rb:83:in `call'"

Looks like `path` is not a valid thing to call on `event`.  The lograge code [accesses a `payload` attribute to get at things like `:params`](https://github.com/roidrage/lograge/blob/62f0e53ca45774447b1853bd72bd1d9f14e4161b/lib/lograge.rb#L65) and another repo [accesses `event.payload[:path]`](https://github.com/honeybadger-io/honeybadger-ruby/blob/82c5299ba3d5f3e928be469d85f26f76fa0da330/lib/honeybadger/init/rails.rb#L80).  Maybe this is what we need?

After the change, please find a way to test this.

**Comment by jpslav** [comment]
cc @kevinburleigh75 since I saw this in -kev logs

**Comment by jpslav** [comment]
@joemsak did you already deal with this?

**Comment by joemsak** [comment]
@jpslav Yes I believe #42 fixed it
