### ISSUE TITLE
Make FindOrCreateResourceFromUrl get canonical URLs from header

### ISSUE THREAD

**Issue by jpslav** [openstax/exchange#46]
Exchange has been timing out on URL fetches of Exercises b/c of Mathjax timing out.  As part of this, Exchange looks for canonical links in the exercise HTML header.  Exercises is going to change (https://github.com/openstax/exercises/issues/84) to put canonical URLs in its header, so hopefully we can take advantage of that and just get the header of the exercise content instead of getting the entire HTML page.

low priority

**Comment by Dantemss** [comment]
This was partially fixed by making Mathjax load async...
